{{- if .Values.hostListener.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hostListenerName" . }}
  labels:
    app: coprocessor-host-listener
    app.kubernetes.io/name: {{ include "hostListenerName" . }}
spec:
  selector:
    matchLabels:
      app: coprocessor-host-listener
      app.kubernetes.io/name: {{ include "hostListenerName" . }}
  endpoints:
  - port: metrics
{{- end -}}
